language: node_js
node_js:
  - "8"
  - "6"
script:
  - npm run commitlint-travis
  - npm test -- --runInBand
sudo: false
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
